# Generated by Django 5.1.3 on 2024-11-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_cancer_detection_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='appointment_url',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='contact_url',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='location',
            field=models.CharField(max_length=200, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='صورة الطبيب'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='التخصص'),
        ),
    ]
