# Generated by Django 5.1.3 on 2024-11-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_cancer_detection_app', '0002_remove_doctor_appointment_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(upload_to='doctor_images/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(max_length=100),
        ),
    ]
