# Generated by Django 5.1.3 on 2024-12-01 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_cancer_detection_app', '0005_rename_location_doctor_address_doctor_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='appointment_url',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='contact_url',
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
